package com.pojo;
// Generated Jul 10, 2019 5:01:50 PM by Hibernate Tools 3.5.0.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartid;
	private Customer customer;
	private String custname;
	private String selectedmedicine;
	private Integer selectedquantity;
	private Double price;
	private Integer total;

	public Cart() {
	}

	public Cart(Customer customer, String custname, String selectedmedicine, Integer selectedquantity, Double price,
			Integer total) {
		this.customer = customer;
		this.custname = custname;
		this.selectedmedicine = selectedmedicine;
		this.selectedquantity = selectedquantity;
		this.price = price;
		this.total = total;
	}

	public Integer getCartid() {
		return this.cartid;
	}

	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getCustname() {
		return this.custname;
	}

	public void setCustname(String custname) {
		this.custname = custname;
	}

	public String getSelectedmedicine() {
		return this.selectedmedicine;
	}

	public void setSelectedmedicine(String selectedmedicine) {
		this.selectedmedicine = selectedmedicine;
	}

	public Integer getSelectedquantity() {
		return this.selectedquantity;
	}

	public void setSelectedquantity(Integer selectedquantity) {
		this.selectedquantity = selectedquantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

}
