package com.pojo;
// Generated Jul 10, 2019 5:01:50 PM by Hibernate Tools 3.5.0.Final

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer sid;
	private String mcompany;
	private String mname;
	private String mdescription;
	private Integer quantity;
	private Double price;
	private String mdate;
	private String edate;

	public Stock() {
	}

	public Stock(String mcompany, String mname, String mdescription, Integer quantity, Double price, String mdate,
			String edate) {
		this.mcompany = mcompany;
		this.mname = mname;
		this.mdescription = mdescription;
		this.quantity = quantity;
		this.price = price;
		this.mdate = mdate;
		this.edate = edate;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getMcompany() {
		return this.mcompany;
	}

	public void setMcompany(String mcompany) {
		this.mcompany = mcompany;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMdescription() {
		return this.mdescription;
	}

	public void setMdescription(String mdescription) {
		this.mdescription = mdescription;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getMdate() {
		return this.mdate;
	}

	public void setMdate(String mdate) {
		this.mdate = mdate;
	}

	public String getEdate() {
		return this.edate;
	}

	public void setEdate(String edate) {
		this.edate = edate;
	}

}
